begin
DROP CONSTRAINT ON (n:ITService) ASSERT n.name IS UNIQUE;
DROP CONSTRAINT ON (n:ITServiceGroup) ASSERT n.name IS UNIQUE;
DROP CONSTRAINT ON (n:Shelf) ASSERT n.name IS UNIQUE;
DROP CONSTRAINT ON (n:Cabinet) ASSERT n.name IS UNIQUE;
DROP CONSTRAINT ON (n:ConfigurationItem) ASSERT n.name IS UNIQUE;
DROP CONSTRAINT ON (n:ServerRoom) ASSERT n.name IS UNIQUE;
DROP CONSTRAINT ON (n:WareHouse) ASSERT n.name IS UNIQUE;
commit